project:
  type: book
  output-dir: docs
  
book:
  title: "ATBC Manual"
  output-file: "atbc-manual"
  author: "ATBC Council"
  date: 11/15/2024
  # date: last-modified
  # original-date: 11/15/2024
  # doi
  url: https://herbvar-network.github.io/herbvar_manual
  pdf-url: https://herbvar-network.github.io/herbvar_manual/herbvar-manual.pdf 
  date-format: long
  license: "This work is licensed under CC BY-NC-SA 4.0. //To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/"
  edition: "v0.9.0"
  cover-image: images/atbc_cover.png
  search: true
  repo-url: https://github.com/HerbVar-Network/herbvar_manual
  repo-actions: [edit]
  downloads: [pdf, epub]
  # sharing: [twitter, facebook]
  reader-mode: false
  favicon: images/atbc_favicon.png
  page-footer:
    left: |
      ATBC Manual
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    
    - part: "Bylaws and Key Policies"
      chapters: 
        - 01_intro/mission_statement.qmd
        - 01_intro/bylaws.qmd
        - 01_intro/coi.qmd
        
      
    - part: "Nominatins & Elections"
      chapters: 
        - 02_elections/elections.qmd
        
        
    - part: "Awards" 
      chapters:
        - 03_awards/awards.qmd
        
    
    - part: "Annual Meetings"
      chapters: 
        - 04_conferences/meetings.qmd
        # - 04_protocols/spp_site_selection.qmd
        # - 04_protocols/primary.qmd
        # - 04_protocols/damage.qmd
        # - 04_protocols/repro_damage.qmd
        # - 04_protocols/low_density.qmd
        # - 04_protocols/succulents.qmd
        # - 04_protocols/tree.qmd
        # - 04_protocols/rhizo_geo.qmd
        # - 04_protocols/herbivore.qmd    
    
    - references.qmd
    
    # - part: "Appendix 1: Forms & Checklists"
    #   chapters: 
    #     - 05_forms/onboarding_checklist.qmd
    #     # - 05_forms/data_sharing_contract.qmd
    #     - 05_forms/forms_list.qmd
    #     - 05_forms/glossary.qmd
    #     
    # - part: "Appendix 2: HerbVar Admin"
    #   chapters: 
    #     - 06_admin/potential_collaborators.qmd
    #     - 06_admin/manual.qmd
    #     - 06_admin/website.qmd
    #     - 06_admin/data_portal.qmd
    #     - 06_admin/google_drive.qmd
    #     - 06_admin/wrangling_repo.qmd
    # 
bibliography: HerbVar.bib
csl: format/ecology.csl
format:

  html:
    theme: 
      - cosmo
      - format/r4ds.scss
      
  pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    cover-image: images/atbc_cover.png
    # template-partials:
    #   - "04_protocols/title.tex"
    header-includes: |
      \titlehead{\includegraphics[height=9in]{images/atbc_cover.png}}
      \publishers{v0.9.0 (Zenodo https://doi.org/10.5281/zenodo.14232308)\\-\\This material is based upon work supported by the National Science Foundation under Award No. NSF DEB-2203582.\\-\\Licensed under CC BY-NC-SA 4.0.}
    toc: true
    toc-depth: 2
    toc-title: Table of Contents
    lof: true
    lot: true
    bibliography: HerbVar.bib
    # Numbering
    number-sections: true
    # Fonts
    # fontfamily: libertinus
    # mainfont: Georgia
    # sansfont: Verdana
    # monofont: Source Code Pro
    # fontsize: 12pt
    microtypeoptions: ["final"]
    # Colors
    colorlinks: true
    # Layout
    geometry:
      - margin=1in
      - bindingoffset=0.5in
      # - left=24mm
      # - top=24mm
      # - bottom=24mm 
      # - right=50mm
      # - heightrounded
      # - footskip=0.475in
      # - showframe
    # pagestyle: plain
    # Rendering
    keep-tex: true
    # https://quarto.org/docs/journals/templates.html#template-partials
    # https://github.com/quarto-dev/quarto-cli/discussions/1941
    # https://tex.stackexchange.com/questions/209993/how-to-customize-my-titlepage/210280#210280
    # https://github.com/nmfs-opensci/quarto_titlepages_v1
    # https://nmfs-opensci.github.io/quarto_titlepages_v1/03-how-to-use.html
    # https://tex.stackexchange.com/questions/209993/how-to-customize-my-titlepage/210280#210280
    # https://nrennie.rbind.io/blog/pdf-quarto/making-pretty-pdf-quarto/
    # https://github.com/nrennie/PrettyPDF

    # include-in-header: 
    #  - "format/PrettyPDF.tex"
    # include-before-body:
    #  - "format/pagestyle.tex
    #   - "format/_titlepage.tex" 
  
      
  epub:
      epub-cover-image: images/atbc_cover.png

# pdf-engine: xelatex
# see fpr engine-opt: https://stackoverflow.com/questions/74261557/quarto-rendering-pdf-running-xelatex-faster-in-rstudio    
editor: source

execute:
  freeze: auto