---
title: Bylaws 
title-block-style: plain
# date: 09/15/2024
# date-modified: last-modified
---

# Bylaws {#sec-bylaws}

THE ASSOCIATION FOR TROPICAL BIOLOGY AND CONSERVATION

BYLAWS

_(As Amended and Revised through ATB Membership Vote Tabulated April 1973;
through ATB Membership Vote Tabulated May 1994; through ATB Membership Vote Tabulated March 2001; through ATB Membership Vote Tabulated December 2002; through ATBC Membership Vote Tabulated March 2013; and through ATBC Membership Vote Tabulated November 2020)_


## ARTICLE I: Organization and Objectives

### Section 1. Organization. 

The Association for Tropical Biology, Inc., also known as The Association for Tropical Biology and Conservation (hereafter called "The Association") is a membership corporation organized pursuant to the Membership Corporation Law of the State of New York of the United States of America. The Association is international in scope, membership, and objectives, functioning as an international body to promote research, education, communication, and increased public awareness for tropical biology and conservation.
### Section 2. Objectives. The objectives of The Association are:

(a) To promote research in all aspects of tropical biology and conservation. 
(b) To promote education in tropical biology and conservation. 
(c)	To promote and improve communication and cooperation among investigators, educators, environmental managers, and human communities in the tropics. 
(d) To encourage the establishment, improvement, maintenance and accessibility of physical facilities, databases, and collections of biological materials for the study of tropical biology and conservation.
(e) To promote an awareness, within as wide a public as possible, of the importance of tropical biology and conservation. 
(f) To inform and influence individuals and institutions whose decisions affect tropical habitats and their biota.
(g) To encourage the preservation of tropical biological diversity and to safeguard it for posterity, for its intrinsic worth and its aesthetic and tangible values to humanity. 

## ARTICLE II: Memberships and Dues

### Section 1. Classes of Members. 

There shall be four classes of members, to be designated and constituted as follows:
(a) Founder Members. Founder members are active members who shall have joined The Association before July 1, 1963. The persons signing the Certificate of Incorporation shall also be founder members.
(b) Active Members. Active members are members who pay the dues required pursuant to these Bylaws. II
(c) Patron. Any active member who contributes to The Association in a single installment an amount equivalent to at least 25 times the current dues rate for high income countries will be considered a Patron, retain all privileges of active membership, and be exempt from additional payments for life.
(d) Honorary Fellows. Honorary Fellows are elected by the Council in recognition of their distinguished service to tropical biology or conservation and for their efforts to advance the objectives of The Association. They shall have the same privileges as active members and shall not be liable for any dues or other assessments. 

### Section 2. Admission to and Termination of Membership. 

##### Section 2.1. Admission.

Any person or institution may be admitted to membership upon payment of dues, or upon such other terms and conditions as the Council may provide. Members have voting rights, may be elected to office, may serve as members of committees, and may join The Association's Sections and Regional Chapters.

##### Section 2.2. Termination of Membership.
(a) Grounds for Termination: The membership of an individual shall terminate upon the occurrence of any of the following events:
(i) A failure to renew membership by paying dues on or before their due date.
(ii) Notice of resignation delivered to the President or Secretary of The Association personally, or by (e-)mail; such membership will terminate when the notice is received by The Association, unless a later date is specified in the notice.
(iii) A determination by at least two-thirds of the voting Council that the member has engaged in conduct that is seriously prejudicial to the interests, reputation, or objectives of The Association and should be expelled from The Association.
(b) Procedure of Expulsion: Following determination that a member should be expelled under this section, the following procedures shall be implemented:
(i) A written notice shall be sent to the member's address for correspondence as shown in the ATBC's records, setting forth the expulsion and the reasons therefore. Such notice shall be sent at least fifteen days prior to the proposed effective date of the expulsion.
(ii) The member being expelled shall be given an opportunity to be heard, either orally or in writing, at a hearing to be held not less than five days before the effective date of the proposed expulsion. The hearing shall be held by the Council in accordance with the quorum and voting rules applicable to the meetings of the Council. The notice to the member of their proposed expulsion shall state the date, time, and place of the hearing on their proposed expulsion. The member and the Council members may participate via conference call or other means by which everyone participating in the hearing may hear all the others.
(iii) Following the hearing, the Council shall decide whether or not the member should in fact be expelled, suspended, or sanctioned in some other way. At least two-thirds of the voting members of the Council must agree upon the suitable course of action. The decision of the Council shall be final.
All rights of a member in The Association shall cease on termination of membership as herein provided.

### Section 3. Dues. 

Dues shall be payable in United States currency, or as the Council shall otherwise provide, on the first business day of each calendar year. The dues rate for each membership category shall be set by the Council.


## ARTICLE III: Officers

### Section 1. Executive Board. 

The Officers of The Association are the members of the Executive Board, which shall consist of a President, a Past-President, a President-Elect, an Editor, a Secretary, one or two      Treasurer(s), and an Executive Director. No two Officer positions may be filled simultaneously by the same person. The Executive Board shall have and may exercise to the fullest extent permitted by law all powers of the Council when the Council is not in session.

### Section 2. The President. 

The President shall preside at meetings of the Executive Board, members, and the Council and shall perform all other duties pertaining to the office or properly required of them by the Council. The President is the primary spokesperson of The Association and serves as a liaison to other societies, government officials, and the public on behalf of The Association.

### Section 3. 

The Past-President. The Past-President of The Association whose term of office terminated most recently, other than by reason of resignation or expulsion, shall serve as an advisor to the President and the Council.

### Section 4. The President-Elect. 

The President-Elect shall have such powers and shall perform such duties as may be assigned by the Council or the President. In the absence or disability of the President, all powers of the President shall be vested in, and all duties of the President shall be performed by, the President-Elect. 

### Section 5. The Editor. 

The Editor shall be responsible for editing, publishing, and overseeing the budget of such publications of The Association as are assigned by the Council. 

### Section 6. The Secretary. 

The Secretary shall be responsible for: (a) scheduling Council meetings and keeping and reporting minutes of all meetings of the Council and General Members’ Meetings; (b) overseeing elections; (c) witnessing delegations of financial authority to other Council members, (d) transferring all records and files to their successor upon completion of their term of office; (e) maintaining The Association's logo and stationary; and (f) maintaining an up-to-date register of members. In case of inability to attend Council meetings, the Secretary shall be represented by a Councilor or other member appointed by the presiding Officer.

### Section 7. The Treasurer(s).  

One or two Treasurers shall have custody of funds and securities of The Association, except as otherwise provided by the Council; shall deposit all monies and other valuable effects in the name and to the credit of The Association in such depositories as may be designated by the Council; shall disburse the funds of The Association as may be ordered by the Council; shall cause full and accurate accounts of receipts and disbursements to be kept; shall render to the President and the Councilors, whenever they may require it, an accounting of all transactions as Treasurer(s) and of the financial condition of The Association; and shall perform all other duties pertaining to the office or properly required by the Council. The Council requires that the Treasurer(s) execute a fidelity bond on the Office satisfactory to it in amount, form, and surety of sureties. 

### Section 8. The Executive Director. 

The Executive Director shall be the Chief Executive Officer of The Association; provide continuity in the execution of policies and programs of The Association; further coordination among The Association’s Officers; work with the Council to develop and implement a strategic plan; make and sign bonds, mortgages, contracts, and other instruments in the name and on behalf of The Association, except when the Council by resolution instructs the same to be done by some other Officer or agent; effect coordination, continuity, and cohesion in the work of The Association, especially vis-a-vis its several working committees; shall assist and support the administration of the President’s office; and shall perform such other duties as may be assigned by the President and the Council.


## ARTICLE IV: The Council

### Section 1. Number. 

The affairs of The Association shall be managed by a Council consisting of the President, Past-President, President-Elect, nine elected Councilors, and the Chair of each Regional Chapter. If the Chair of a Regional Chapter is an elected Councilor or an Officer, then that Chapter shall be represented by the Chapter's Co-Chair, Secretary, or Treasurer, in that order. The Editor, Secretary, Treasurer(s), and Executive Director shall be ex officio members of the Council, but shall not vote on any matter to come before the Council. In the case of a tie vote of the Council, the President shall decide the outcome.

### Section 2. Responsibilities. 

The Council is the executive and policy-making body of The Association and has all powers granted to a board of directors of a nonprofit membership public benefit corporation of the State of New York. It shall, among other duties, ensure that the best and most relevant science is incorporated into all activities of the Association; appoint the Editor-in-Chief of The Association's publications; approve the budget in advance to proposed annual expenditures; decide locations of future conferences and members’ meetings; propose dues adjustments and other fees to the general membership; decide upon the suitability of publications, position papers, or statements to be issued in the name of The Association; decide upon motions of censure or expulsion; establish and abolish standing committees; oversee legal aspects of The Association's operation; and assist the President in carrying out the executive work of The Association. Council members work on various committees and projects. In the performance of their duties as members of the Board of Governors, representatives of Regional Chapters have a primary fiduciary duty to The Association as a whole. The Council may not amend the Bylaws of The Association; nor may it incur financial obligations beyond the actual content of the treasury.


## ARTICLE V: Election, Appointment, Term, and Removal of Officers and Councilors

### Section 1. Nominations and Elections. 

Nominations for elected positions (President-elect and Councilors) shall be directed to a nominating committee formed each year consisting of the Past-President, who chairs the committee, the President-Elect, the President, and two members in good standing with The Association appointed by the Past-President. The additional members shall be chosen to ensure representation of different geographical regions. The committee shall solicit and review candidates for Councilors and President-Elect from the Council and membership of The Association. Upon review of nominations, the committee shall present a final list in writing to the Executive Director and the Secretary, during the month of October, the names of candidates to serve during the next fiscal year beginning January 1. The committee shall place in nomination the names of one or more members for each of the three Councilor positions to be filled. Any candidate must have indicated beforehand their willingness to serve if elected. Nominations should reflect the full diversity and international character of The Association's membership.  

The Secretary shall prepare ballots setting forth the nominations so reported. The Secretary shall cause such a ballot to be distributed by electronic communication during the month of November to each member eligible to vote. Each Active Member, Patron, and Honorary Fellow in good standing shall be entitled to cast one vote for each position to be filled. The Secretary, not less than 30 days after the distribution of ballots, shall inform the President in writing of the results of the election. The President shall cause such results to be announced to the members of The Association in a manner indicated as suitable by the Council.  

### Section 2. The President-Elect. 

The person elected as President-Elect shall serve in that office for a term of one year, or until a successor shall have been elected and shall have qualified; shall serve as President for a term of one year thereafter or until a successor shall have qualified; and shall serve as Past-President for a term of one year thereafter. No person shall be so elected for more than one term. 

### Section 3. 

The Elected Councilors. Each person elected as Councilor shall serve in that office for a term of three years, beginning January 1, or until a successor shall have been elected and shall have qualified. No person shall be so elected for more than one term. 


### Section 4. 

Appointment and Duration of Officers. All officers other than the President, Past-President, and President-Elect shall be appointed by the Council for a 5-year term. For each office, a search committee of at least five members shall be formed of current members of the Council by the President and a recommendation posed to the Council. All officers may serve no more than two consecutive terms in an office.

### Section 5. 

Resignation, Removal, and Vacancies. Any Officer or elected Councilor may resign at any time and, unless otherwise stated therein, such resignation is to take effect upon receipt by the Secretary or President of The Association of written notice thereof. Any Officer appointed by the Council or elected member of the Council may be removed from office at any time by the concurring vote of two-thirds of the Council following the policy and procedures described in ## ARTICLE II ### Section 2(2)(iii) of these bylaws.   

A vacancy in the office of the President shall be filled by the President-Elect, who shall therefore cease to be President-Elect and who shall complete the term of the predecessor prior to entering upon the normal term as President. At the discretion of the Council, a vacancy in the office of President-Elect shall be filled by the concurring vote of a simple majority of the Council or by a special election among the members, or this office may be left vacant until the next regular election.   

A vacancy among the elected Councilors shall be filled by a concurring vote of a simple majority of the members of the Council then in office. A Councilor so elected shall hold office for the unexpired term in respect of which such vacancy occurred.  


A vacancy in the office of the Executive Director, Treasurer, or Secretary shall be filled by an ATBC member nominated by the President and approved by a simple majority of the Council to serve in an interim role until an Officer can be selected. Within 30 days of the vacancy, the President shall appoint a search committee to select the Officer using the process described in ARTICLE V Section 4.

## ARTICLE VI: Meetings

### Section 1. Annual Meeting of the Membership.  

The Association will conduct Annual Meetings of members and the Council once each calendar year with such a time, place, and format as the Council may determine.

### Section 2. Special Meeting.  

Special meetings of the members shall be called by the Secretary upon direction of the President, the Council, or at least one-third of the members. Such meetings shall be held at such time and place and for such purpose or purposes as shall be specified in writing by the person or persons at whose direction the meeting is called.

### Section 3. 

Notice of Meetings. Written notice stating the place, day and hour of the meeting, and the purpose or purposes for which the meeting is called, shall be delivered in writing not less than thirty days before the meeting, by or at the direction of the Chair or the Secretary or other officer or person calling the meeting, to each member in good standing at the physical or electronic mailing address recorded on the membership roll. For the purpose of determining members entitled to vote at any meeting or recess thereof, or in order to make a determination of members for any other proper purpose, the Council shall close the membership roll thirty days immediately prior to the date on which the particular action requiring such determination of members is to occur, and the members on the roll on that date shall constitute the membership for that purpose.  

### Section 4. 

Quorum for the Annual and Special Meetings of the Members. Except as otherwise provided by law or by the Certificate of Incorporation or by other certificate filed pursuant to law or by these Bylaws, the members in attendance at an announced meeting (whether in person or via electronic means) shall be the voting body for such business as may be referred to the membership for a vote. The number of members who participate in an election via electronic means will constitute a quorum and shall constitute the voting body for the election of Councilors or Officers. The affirmative vote of a simple majority of members present at a physical meeting or an electronic election shall be necessary for adoption of any matter voted on, unless a greater proportion is required elsewhere in these Bylaws.  

### Section 5. Voting. 

Each active member, Patron, or Honorary Fellow present in person shall be entitled to one vote at all meetings of members. No proxy votes shall be valid at meetings of members. Officers and Councilors shall be elected by electronic ballot or otherwise appointed pursuant to ## ARTICLE V of these Bylaws. All other questions referred to the members by the Council shall also be decided in a manner indicated as suitable by the Council, either by voting at a meeting of members or by electronic ballot.


### Section 6. Questions of Order or Procedure. 

The Officer presiding at any meeting of members may rule on questions of order or procedure coming before the meeting. The latest edition of Robert's Rules of Order will be utilized for conducting the meetings.


### Section 7. Meetings of the Council. 

The Council shall convene no less than three times annually, by conference call or in person. Special meetings of the Council may be called by the President or by a simple majority of Council members. Notice of time and place of every meeting of the Council shall be communicated to each member of the Council not less than 30 days before the meeting by the Secretary. Any one or more individuals may participate in a meeting of the Council by means of a conference telephone or other electronic technologies that allows all persons participating in the meeting to hear each other. Participation by such electronic communications shall be equivalent to presence in person at the meeting for purposes of determining if a quorum is present. The Editor, Secretary, Treasurer(s), and Executive Director, as ex officio members of the Council, may not vote. Except as otherwise required by law or by the Certificate of Incorporation or by other certificate filed pursuant to law or by these By-Laws, the presence at any meeting of the Council of at least a simple majority of voting members of the Council shall constitute a quorum for the transaction of all business. The Council may also transact business by mail or email.


## ARTICLE VII: Committees, Regional Chapters, and Thematic Sections

### Section 1. Committees, Regional Chapters, and Thematic Sections. 

The Council shall establish and maintain an up-to-date Handbook that describes the structure, procedures, and operating guidelines for Committees, Regional Chapters, and Thematic Sections of The Association.

### Section 2. Standing Committees.


#### Section 2.1. Charges. 

Committee status shall be granted to those Committees with continuing, long-term responsibilities to The Association. Committees require a direct charge by the Council or Executive Director. Committees should develop procedures for, and/or implement the Society's strategic plan. Each standing committee submits a report of its activities to the President for review and approval by the Council at least annually, unless otherwise specified. 

#### Section 2.2. Chairs. 

The Executive Director receives from the other Officers and Councilors nominations for Chairs of Committees. The Executive Director, in consultation with the Executive Board, appoints standing committee Chairs from the nominations submitted or requests additional nominations. Chairs of Committees may be duly elected members of the Council, or any other members-in-good-standing of The Association. The term of a standing committee Chair is three years. Committee Chairs shall be eligible for reappointment only once. The Chairs of a standing committee may be removed from office by a two-thirds vote of the Council. A committee chair may also resign at any time and, unless otherwise stated therein, such resignation is to take effect upon receipt by the Secretary of The Association of written notice thereof.


#### Section 2.3. 

Committee members. Committee members shall be solicited from The Association's current membership. The Chair of each Committee shall appoint Committee members, at least one of whom shall be a current Council member, in consultation with the Executive Director. Members of any Committee must be members of The Association in good standing and should reflect the full diversity and international character of The Association’s membership. The terms of standing committee members are for three years, unless otherwise specified or unless appointed to complete a vacant position. Committee members cannot serve on more than two committees at a time and shall be eligible for reappointment only once. Any committee member may resign at any time and, unless otherwise stated therein, such resignation is to take effect upon receipt of a written communication by the Committee Chair. Any committee member may be removed from the committee at any time without cause being assigned by the concurring vote of a simple majority of the Council. Vacancies in any committee may be filled at any meeting of the Council or by mail consensus. 

#### Section 2.4. Meetings. 

Each standing committee shall meet at least once a year electronically or in person. The committee Chair shall submit a report of the committee’s activities to the President as described in ARTICLE VIII.


#### Section 2.5. Support. 

Financial support for Standing Committees shall be determined by the Council and designated in the budget.

### Section 3. Special Committees.


### Section 3.1. Charges. 

The President, President-elect, or the Council may establish or dissolve by resolution of the Council special committees as deemed necessary to conduct the work of The Association, subject to the approval of the Council. The composition, size, purpose, and powers of each special committee shall be provided in any such resolution. Except as otherwise provided in such resolution or these Bylaws, the President, and Executive Director shall be ex officio on each special committee. Special committees shall be dissolved no later than the end of the term of the President, unless otherwise determined by resolution of the Council.

#### Section 3.2. Chairs and Liaisons. The President shall make two initial appointments: a Chair of the special committee, who shall be a member of the ATBC, and a Liaison, who shall be a member of the Council.

#### Section 3.3. Members. The President and Chair shall confer on special committee members, who shall be appointed by the President.

#### Section 3.4. Meetings. Each special committee shall present a report to the President before each Council meeting and a report to the Council before the Annual Meeting.

#### Section 3.5. Support. Financial support for a special committee shall be determined by the Council in response to a request from the President.

#### Section 3.6. Reporting. Each special committee shall submit a report of its activities to the President for approval by the Council within one year unless otherwise specified.

### Section 4. Regional Chapters. 

#### Section 4.1. Purpose. Regional Chapters pursue the objectives of The Association in a geographic region and enhance communication among members living or working in that region.

#### Section 4.2. Creation, Dissolution, and Manner of Acting.

(a) Creation. One percent or more of members of The Association may petition for the establishment of a Chapter. The petition must include a draft Memorandum of Understanding (MOU) between The Association and the Regional Chapter, including specific language regarding the purpose of the Chapter and benefits it will provide to members; a statement, plan, and timeframe for the Chapter to be established and hold elections; and a draft of Chapter bylaws. A majority of the Council must vote to approve the proposed Chapter bylaws and MOU. Subsequent changes to the Bylaws and MOU must be submitted to the Council for approval. The MOU must be reviewed and either re-approved or amended at least once every three years.
(b) Dissolution. If a Regional Chapter is inactive for two or more years, a Chapter may be discontinued by a majority vote of the Council. The Council may also suspend or revoke a Chapter at any time for not operating in accordance with the MOU, The Association's bylaws, policies, or purposes, or for jeopardizing The Association fiscally or legally by majority vote.
(c) Manner of Acting. Each Regional Chapter shall be governed as specified in a set of bylaws approved by the Council. Chapters may arrange and operate their own programs and activities, so long as these do not conflict with, or encroach upon, the activities of The Association or other Sections and Chapters and conform to The Association's policies.

#### Section 4.3. Regional Chapter Chairs. 

Each Regional Chapter shall elect a Chair by the procedure described in their bylaws. The Chair shall be the representative of the Regional Chapter on the Council and present the report of Chapter activities to the Council once per year.

#### Section 4.4. Members. 

Any person of any class of membership in The Association may become a member of any Regional Chapter by signifying a desire to join on the annual dues notice of The Association and by payment of Regional Chapter dues, if any.

#### Section 4.5. Liabilities. 

Each Regional Chapter is responsible for its own legal and fiscal liabilities, unless specifically stated otherwise by resolution of the Council. Regional Chapters may request grants and loans from The Association, to be evaluated by the Treasurer(s) and the Executive Director for Council action. Each Regional Chapter must provide an annual fiscal report and report of activities to the Council.  

### Section 5. Thematic Sections. 

Thematic Sections promote communication and collaboration on topics of interest to the Membership. Any member-in-good-standing of the Association may join a ### Section by signifying a desire to join on the annual dues notice. New Sections may be established by majority approval of the Council to a formal petition by any member of the Association. Sections may arrange and operate their own programs and activities, so long as these do not conflict with or encroach upon the activities of The Association or other Sections and Chapters and conform to The Association's policies.


## ARTICLE VIII: Annual Reports

Once per year, at a Council Meeting, the Secretary, the Treasurer(s), Editor, Regional Chapter Chairs, and Committee Chairs shall present progress reports to the President and Executive Director for compilation and making available to the members. All reports shall be made publicly available to The Association's members.


## ARTICLE IX: Conflicts of Interest

	The Association shall maintain a Conflicts-of-Interest Policy to ensure that all elected and appointed officers, persons in leadership positions, and employees are acting strictly in the best interests of the Society. Potential conflicts of interest include situations in which a person in a position of authority in the organization may benefit financially from a decision they could make in such capacity, including indirect benefits such as to family members or businesses with which they are closely associated. The policy will assist the Executive Director, officers and others in the organization in identifying, evaluating, and resolving conflicts of interest. The policy is intended to supplement, but not replace, any applicable state and federal laws governing conflicts of interest applicable to nonprofit and tax-exempt organizations.


## ARTICLE X: Indemnification

Any person made a party to any action, suit, or proceeding by reason of the fact that the person, the person’s testator, or intestate, is or was a councilor, officer, or employee of The Association or of any corporation which the person served at the request of The Association, shall be indemnified by The Association against the reasonable expenses, including attorneys’ fees, actually and necessarily incurred by the person in connection with the defense of such action, suit, or proceeding, or in connection with any appeal therein, except in relation to matters as to which it shall be adjudged in such action, suit, or proceeding that such officer, councilor, or employee is liable for negligence or misconduct in the performance of the person’s duties. Such right of indemnification shall not be deemed exclusive of any other rights to which such councilor, officer, or employee may be entitled.


## ARTICLE XI: Miscellaneous

### Section 1. Waiver of Notice. 

Whenever The Association or the Council is authorized to take any action after notifying its members or after the lapse of a prescribed period of time, such action may be taken without notice and without lapse of any period of time, if such action be authorized or approved and if at any time before or after such action be completed such requirements be waived in writing by the person or persons entitled to said notice or to participate in such action, or, in the case of a member of The Association, by the person’s attorney thereunto authorized.


### Section 2. Seal. 

The Seal of The Association shall be circular in form and shall contain the name of The Association, the year of its organization, and the words, CORPORATE SEAL, NEW YORK.

### Section 3. Fiscal Year. 

The fiscal year of The Association shall commence on the first business day of January.

### Section 4. Language. 

These Bylaws may be translated into any language at the direction of the Council; however, the official and legal version shall be that in the English language.


## ARTICLE XII: General Prohibitions

Any provisions of these Bylaws which might be susceptible to a contrary construction notwithstanding:
(1) The Association is organized and operated exclusively for scientific and education purposes.

(2) No part of the assets of The Association shall, or may, under any circumstances, inure to the private benefit of any member, officer, or individual except as reasonable compensation for services or reimbursement for approved personal expenditures on behalf of The Association.
(3) Whereas The Association exists for scientific and educational purposes, it may engage in efforts intended better to inform the public on issues pertaining to tropical biology and conservation and the influences of tropical ecosystems on humankind as an element in the biosphere. The Association, nevertheless, shall not allow any part of its activities to become those of lobbying or espousing particular scientific, economic, political, social, or religious doctrines or dogmas.
(4) The Association shall not participate in, or intervene in (including the publishing or distributing of statements), any political campaign on behalf of a candidate for public office.
(5) The Association shall not be organized or operated for profit.
(6) The Association shall not: 
(a) lend any part of its income or corpus without the receipt of adequate security and a reasonable rate of interest to;
(b) pay any compensation in excess of a reasonable allowance for salaries or other remuneration for personal services actually rendered to;
(c) make any part of its services available on a preferential basis to;
(d) make any purchase of securities or any other property for more than adequate consideration in money’s worth from;
(e) sell any securities or other property for less than adequate consideration in money or money’s worth to; or
(f) engage any other transactions which result in a substantial diversion of its income or corpus to any member, officer, member of the Council, or substantial contributor to The Association.
The prohibitions contained in this ### Section (6 a-f) do not mean to imply that The Association may make such loans, payments, sales, or purchases from or to anyone else, unless such authority be given or implied by other provisions of these Bylaws.

## ARTICLE XIII: Distribution on Dissolution

Upon dissolution of The Association, the Council distributes the assets and accrued income to one or more scientific and educational organizations recognized as not-for-profit, 501 c(3) entities under the United States Internal Revenue Code.


## ARTICLE XIV: Amendment

Amendments to these Bylaws may be proposed in writing by any member to the Secretary, who shall submit them to the President and Council for consideration. Such proposed amendments as have been approved by the Council shall be submitted to the members for ballot by mail. The Secretary shall cause such a ballot to be mailed, e-mailed, or to be served personally upon each member eligible to vote. Not less than 30 days and not more than 60 days after the distribution of ballots, the Secretary shall inform the President in writing of the results of the ballot. For the adoption of the proposed amendments a favorable vote of a majority of the eligible members who return their ballots is necessary. The President shall cause such results to be announced to the members of The Association in a matter indicated as suitable by the Council.
