---
title: COI Policy 
title-block-style: plain
# date: 09/15/2024
# date-modified: last-modified
---

# Conflict of Interest Policy {#sec-coi}

Conflict of Interest and Compensation Policy of The Association for Tropical Biology & Conservation (“the Association”)

Adopted 01 May 2021

## Overview

### Purpose 

The purpose of this Conflict of Interest and Compensation Policy (the “policy”) is to protect the Association’s interests when entering into a transaction that might benefit the private interests, result in the payment of excessive compensation, or violate state and federal laws of members of the ATBC Council or Key Person. 

### Why is a policy necessary? 

As a nonprofit, charitable organization, the Association is accountable to both government agencies and members of the public for responsible and proper use of its resources. Members of the Council or Key Persons have a duty to act in the Association’s best interests and may not use their positions for their own financial or personal benefit.

Conflicts of interest must be taken very seriously since they can damage the Association’s reputation and expose both the Association and affiliated individuals to legal liability if not handled appropriately. Even the appearance of a conflict of interest should be avoided, as it could undermine public support for the Association.

### To whom does the policy apply?

This policy applies to all members of the ATBC Council and Key Persons (“you”).  


## Identifying Conflicts of Interest


### What is a conflict of interest? 

A potential conflict of interest arises when a member of the Council, or Key Person, or that person’s relative or business (a) stands to gain a financial benefit from an action the Association takes or a transaction into which the Association enters; or (b) has another interest that impairs, or  could be seen to impair, the independence or objectivity of the Council Member or Key Person in discharging their duties to the Association.  

###  What are some examples of potential conflicts of interest?

It is impossible to list all the possible circumstances that could present conflicts of interest. Potential conflicts of interest include situations in which a Council Member or Key Person or that person’s relative or business: 
i. has an ownership or investment interest in any third party that the Association deals with or is considering dealing with; 
ii. serves on the board of, participates in the management of, or is otherwise employed by or volunteers with any third party that the Association deals with or is considering dealing with; 
receives or may receive compensation or other benefits in connection with a transaction into which the Association enters; 
iii. receives or may receive personal gifts or loans from third parties dealing with the Association;
iv. serves on the board of directors of another nonprofit organization that is competing with the Association for a grant or contract; 
v. has a close personal or business relationship with a participant in a transaction being considered by the Association;
vi. would like to pursue a transaction being considered by the Association for  their personal benefit. 

In situations where you are uncertain, err on the side of caution and disclose the potential conflict as set forth in Section III of this policy. 

A potential conflict is not necessarily a conflict of interest. A person has a conflict of interest only if the audit committee decides, pursuant to Section IV of this policy, that a conflict of interest exists. 


## Disclosing Potential Conflicts of Interest

All Council Members and Key Persons must file an annual disclosure statement with the ATBC Treasurer using the form attached to this policy. 

Candidates for elected or appointed office must also file this statement to the chair of the audit committee prior to their initial election.

You must disclose to the best of your knowledge all potential conflicts of interest as soon as you become aware of them and always before any actions involving the potential conflict are taken.  Submit a signed, written statement disclosing all the material facts to the audit committee. 


### Determining Whether a Conflict of Interest Exists 

After there has been disclosure of a potential conflict and after gathering any relevant information from the concerned Council Member or Key Person, an audit committee shall determine whether there is a conflict of interest. The Council Member or Key Person shall not be present for deliberation or vote on the matter and must not attempt to improperly influence the determination of whether a conflict of interest exists. 

In determining whether a conflict of interest exists, the audit committee shall consider whether the potential conflict of interest would cause a transaction entered into by the Association to raise questions of bias, inappropriate use of the Association’s assets, or any other impropriety.  

A conflict always exists in the case of a related party transaction – a transaction, agreement or other arrangement in which a related party has a financial interest and in which the Association or any affiliate of the Association is a participant. 

If the audit committee determines that there is a conflict of interest, it shall refer the matter to the ATBC Council (“board”).


### Procedures for Addressing a Conflict of Interest 

When a matter involving a conflict of interest comes before the board, the board may seek information from the Council Member or Key Person with the conflict prior to beginning deliberation and reaching a decision on the matter.  However, a conflicted person shall not be present during the discussion or vote on the matter and must not attempt to improperly influence the deliberation or vote.

### Additional Procedures for Addressing Related Party Transactions

The Association may not enter into a related party transaction unless, after good faith disclosure of the material facts by the Council Member or Key Person, the Council or a committee authorized by the Council determines that the transaction is fair, reasonable and in the Association's best interest at the time of such determination. 

If the related party has a substantial financial interest, the board or authorized committee shall:

prior to entering into the transaction, consider alternative transactions to the extent available;

approve the transaction by a vote of not less than a majority of the Councilors present at the meeting; and

contemporaneously document in writing the basis for its approval, including its consideration of any alternative transactions.


### Minutes and Documentation 

The minutes of any board meeting at which a matter involving a conflict of interest or potential conflict of interest was discussed or voted upon shall include: 

the name of the interested party and the nature of the interest;

the decision as to whether the interest presented a conflict of interest;

any alternatives to a proposed contract or transaction considered by the board; and 

if the transaction was approved, the basis for the approval.


### Prohibited Acts

The Association shall not make a loan to any Officer, or Councilor, or Key Person.


### Confidentiality

Members of the Council and Key Persons shall exercise care not to disclose confidential information acquired in connection with such status or information the disclosure of which might be adverse to the interests of the Association. 

Members of the Council and Key Persons shall not disclose or use information relating to the business of the Association for their personal profit or advantage of a family member.

Procedures for Determining Compensation 

No person shall be present for or participate in board or committee discussion or vote pertaining to:
their own compensation; 
the compensation of their relative; 
the compensation of any person who is in a position to direct or control them in an employment relationship; 
the compensation of any person who is in a position to directly affect their financial interests; or 
any other compensation decision from which the person stands to benefit.

In the case of compensation of Key Persons, the following additional procedures apply:
The Council or a committee authorized by the Council shall approve compensation before it is paid.
The Council or authorized committee shall base approval of compensation on appropriate data, including compensation paid by comparable organizations (three are sufficient if the Association’s income is less than $1,000,000) for functionally similar positions, availability of similar services in the geographic area of the Association, and compensation surveys compiled by independent firms. 
The board or authorized committee shall contemporaneously document:
the terms of compensation and date of determination;
the members of the board or committee who were present and those who voted for it;
the comparability data relied on and how it was obtained;
if the compensation is higher or lower than the range of comparable data, the basis for the determination, and;
any actions with respect to consideration of the compensation by anyone on the board or committee who had a conflict of interest with respect to the matter.

### Reviewing and Updating the Conflict-of-Interest and Compensation Policy

This policy shall be reviewed annually by members of the Council and other Key Persons.

Members of the Council may propose changes to the policy at any time.

Proposed changes to the policy are approved by the Council with a simple majority vote.





DOCUMENT HISTORY 
DRAFT: 22 April 2021
ADOPTED: 01 MAY 2021



Association for Tropical Biology and Conservation 
Conflict of Interest Disclosure Statement

 

By signing below, I affirm that:

I have received and read a copy of the Conflict of Interest and Compensation Policy;

I agree to comply with the policy;

I have no actual or potential conflicts as defined by the policy or if I have, I have previously disclosed them as required by the policy or am disclosing them below.

Disclose here, to the best of your knowledge:

Any entity in which you participate (as a Councilor, Officer, Employee, or Member) with which the Association has a relationship;

Any transaction in which the Association is a participant as to which you might have a conflicting interest; and

Any other situation which may pose a conflict of interest.












Name:

Position:

Signature:

Date:

